
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - deployment.my.domain
  resources:
  - notifications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployment.my.domain
  resources:
  - notifications/finalizers
  verbs:
  - update
- apiGroups:
  - deployment.my.domain
  resources:
  - notifications/status
  verbs:
  - get
  - patch
  - update
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
